Now bind address can be defined in TM_SETTINGS file. Updated gunicorn launch scripts and test to account for this.

diff --git a/bin/gunicorn b/bin/gunicorn
--- a/bin/gunicorn
+++ b/bin/gunicorn
@@ -11,17 +11,42 @@ if [ "$1" == "start" ]; then
 		echo "Please specify a configuration file"
 		exit 1
 	fi
-	echo Staring gunicorn with configuration $TM_SETTINGS and code from $PYTHONPATH
+	msg="Attempting to start gunicorn with\n\tconfiguration: $TM_SETTINGS\n\tcode: $PYTHONPATH"
+	if grep -q '^BIND\s*=' "$TM_SETTINGS"; then
+		bind="$(grep '^BIND\s*=' $TM_SETTINGS | cut -d = -f 2 | cut -d"'" -f 2)"
+		msg="$msg\n\tbind: $bind (as specified by '$TM_SETTINGS')"
+		bind_opt="--bind $bind"
+	else
+		bind=$(grep 'bind\s*=' "$BASEDIR"/etc/gunicorn.conf | cut -d = -f 2 | cut -d"'" -f 2)
+		msg="$msg\n\tbind: $bind (as specified by '$BASEDIR/etc/gunicorn.conf')"
+		bind_opt=""
+	fi
+	echo -e "$msg"
 	rm -f "$BASEDIR"/var/gunicorn.*
 	touch "$BASEDIR"/var/gunicorn.errors
-	tail -n 0 -f "$BASEDIR"/var/gunicorn.errors & pid=$!
-	gunicorn -c "$BASEDIR"/etc/gunicorn.conf \
+
+	gunicorn -c "$BASEDIR"/etc/gunicorn.conf $bind_opt \
 		--access-logfile "$BASEDIR"/var/gunicorn.accesses \
 		--error-logfile "$BASEDIR"/var/gunicorn.errors \
 		--pid "$BASEDIR"/var/gunicorn.pid tm.web:app
 	chmod go= "$BASEDIR"/var/gunicorn.*
-	sleep 1
-	kill $pid
+
+	echo -en "\twaiting for server startup"
+	attempts=10
+	while [[ $attempts > 0 ]] && ! grep -q 'Booting worker with pid' "$BASEDIR"/var/gunicorn.errors; do
+		echo -n .
+		sleep 1
+		attempts=$(( $attempts - 1 ))
+	done
+	if [[ $attempts > 0 ]]; then
+		echo ". started!"
+
+		echo -e "\tdefine sign as:" $(curl -s http://$bind/sign | grep 'sign()' | cut -d'#' -f2)
+
+	else
+		echo " FAILED TO START!"
+		exit 1
+	fi
 
 elif [ "$1" == "tail" ]; then
 
