Fixing install and init scripts

diff --git a/test/server b/test/server
--- a/test/server
+++ b/test/server
@@ -29,27 +29,21 @@ pg() { python -c "from urllib2 import urlopen; print urlopen( 'http://localhost:
 # Start the server (pre-kill all other python stuff: this is not safe!)
 
 killall python 2>/dev/null || true
-if [ -z "$1" ]; then
-	rm -f /tmp/tm_test/{out,err}
-	python -m tm.web prod > /tmp/tm_test/out 2> /tmp/tm_test/err &
-	echo -n "Waiting for server startup"
-	attempts=10
-	while [[ $attempts > 0 ]] && ! grep -q "Running on http" /tmp/tm_test/err; do
-		echo -n .
-		sleep 1
-		attempts=$(( $attempts - 1 ))
-	done
-	if [[ $attempts > 0 ]]; then
-		echo " started!"
-	else
-		echo " FAILED TO START!"
-		exit 1
-	fi
+rm -f /tmp/tm_test/{out,err}
+python -m tm.web > /tmp/tm_test/out 2> /tmp/tm_test/err &
+echo -n "Waiting for server startup"
+attempts=10
+while [[ $attempts > 0 ]] && ! grep -q "Running on http" /tmp/tm_test/err; do
+	echo -n .
+	sleep 1
+	attempts=$(( $attempts - 1 ))
+done
+if [[ $attempts > 0 ]]; then
+	echo " started!"
 else
-	python -m tm.web & sleep 2
+	echo " FAILED TO START!"
+	exit 1
 fi
-
-sleep 2
 
 # Running tests...
 
