Fixed code as per server tests

diff --git a/test/server b/test/server
--- a/test/server
+++ b/test/server
@@ -24,15 +24,15 @@ touch /tmp/tm_server/tar_dir/TEST
 
 # Start the server (pre-kill all other python stuff: this is not safe!)
 
-killall -m '[Pp]ython' 2>/dev/null || true
+pkill -f release/tm 2>/dev/null || true
 ( ./release/tm web > /tmp/tm_server/outerr 2>&1 & )
 port=8000
 
-pg() { python -c "from urllib2 import urlopen; print urlopen( 'http://localhost:$port/$1' ).read()" | python; }
+pg() { python3 -c "from urllib.request import urlopen; print(urlopen('http://localhost:$port/$1').read().decode('utf-8'))" | python3; }
 
 echo -n "Waiting for server startup"
 attempts=10
-while [[ $attempts > 0 ]] && ! grep -qE "Running on http|started" /tmp/tm_server/outerr; do
+while [[ $attempts > 0 ]] && ! grep -q "Start" /tmp/tm_server/uploads/EVENTS-* 2>/dev/null; do
 	echo -n .
 	sleep 1
 	attempts=$(( $attempts - 1 ))
@@ -67,7 +67,7 @@ assert "Upload" "$(/tmp/tm_server/home/tmclient ul ^TEST)" "TEST"
 
 assert "Received upload" "$(tar -C /tmp/tm_server/untar_dir -xvf /tmp/tm_server/uploads/1/*.tar TEST 2>&1)" "TEST"
 
-perl -i -pe 's/49a4405aafe63df05202df08f8f75c9247b7168159c964f697ba6f974ae40588/boo/' /tmp/tm_server/home/tmclient
+perl -i -pe 's/9iMjaoUxRbadTZaTY86tViJisVk/boo/' /tmp/tm_server/home/tmclient
 assert "Client auth error" "$(/tmp/tm_server/home/tmclient ul ^TEST 2>&1)" "Si è verificato un errore inatteso del client!"
 
 touch /tmp/tm_server/uploads/s
@@ -79,8 +79,8 @@ assert "Installation failure" "$(pg s 2>&1)" 'echo "Si è verificato un errore i
 
 assert "Auth error" "$(curl -d signature=x -sL http://localhost:$port/)" '# Firma mancante, o invalida!'
 
-assert "Internal error" "$(curl -d signature='s:31aa7ab3db1f26dae9daf68f664c242d4c9adbcef36506c134c3eed4573f7bdc' -d tar='ERROR' -sL http://localhost:$port/)" '# Si è verificato un errore inatteso del server!'
+assert "Internal error" "$(curl -d signature='s.rDlTBxI4T0wZ4XldsPQ0fscy2Pc' -d tar='ERROR' -sL http://localhost:$port/)" '# Si è verificato un errore inatteso del server!'
 
 # Again, a very unsafe kill all!
 
-killall -m '[Pp]ython' 2>/dev/null || true
+pkill -f release/tm 2>/dev/null || true
